### ISSUE TITLE
Code folding error

### ISSUE THREAD

**Issue by HactarCE** [hjson/atom-hjson#5]
Same as [this issue on the Atom repo](https://github.com/atom/atom/issues/14099).

Steps to reproduce:

1. Create a new file with the `.hjson` extension and write some HJSON
2. Try to fold the code using the arrow on the left side next to the line numbers

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: empty char-class

```
At C:\Users\REDACTED\AppData\Local\atom\app-1.17.2\resources\app\node_modules\oniguruma\lib\onig-reg-exp.js:9

Error: empty char-class
    at Error (native)
    at new OnigRegExp (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/oniguruma/lib/onig-reg-exp.js:9:22)
    at LanguageMode.module.exports.LanguageMode.cacheRegex (~/AppData/Local/atom/app-1.17.2/resources/app/src/language-mode.js:413:1)
    at LanguageMode.module.exports.LanguageMode.foldEndRegexForScopeDescriptor (~/AppData/Local/atom/app-1.17.2/resources/app/src/language-mode.js:430:1)
    at LanguageMode.module.exports.LanguageMode.rowRangeForCodeFoldAtBufferRow (~/AppData/Local/atom/app-1.17.2/resources/app/src/language-mode.js:212:1)
    at LanguageMode.module.exports.LanguageMode.rowRangeForFoldAtBufferRow (~/AppData/Local/atom/app-1.17.2/resources/app/src/language-mode.js:166:1)
    at LanguageMode.module.exports.LanguageMode.foldBufferRow (~/AppData/Local/atom/app-1.17.2/resources/app/src/language-mode.js:152:1)
    at TextEditor.module.exports.TextEditor.foldBufferRow (~/AppData/Local/atom/app-1.17.2/resources/app/src/text-editor.js:3082:1)
    at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (~/AppData/Local/atom/app-1.17.2/resources/app/src/line-number-gutter-component.js:133:1)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/line-number-gutter-component.js:3:1)
```

### Commands

```
     -1:26.5.0 core:delete (input.hidden-input)
  2x -1:26.4.0 core:backspace (input.hidden-input)
     -1:25.5.0 intentions:highlight (input.hidden-input)
     -1:25.4.0 core:save (input.hidden-input)
     -1:19.6.0 core:backspace (input.hidden-input)
     -1:18.9.0 intentions:highlight (input.hidden-input)
     -1:18.8.0 editor:move-to-end-of-word (input.hidden-input)
     -1:18.3.0 core:move-right (input.hidden-input)
     -1:18.2.0 core:delete (input.hidden-input)
     -1:17.9.0 intentions:highlight (input.hidden-input)
     -1:17.8.0 core:save (input.hidden-input)
  3x -1:12.7.0 core:backspace (input.hidden-input)
     -1:11.7.0 intentions:highlight (input.hidden-input)
     -1:11.7.0 core:save (input.hidden-input)
     -1:06.5.0 intentions:highlight (input.hidden-input)
     -1:06.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
behave-theme 1.7.0 
busy-signal 1.4.3 
custom-folds 1.9.4 
flexible-ui 0.10.7 
fold-lines 0.2.2 
fold-navigator 0.0.618 
gruvbox-plus-syntax 1.3.1 
haskell-ghc-mod 1.19.9 
haskell-pointfree 0.2.0 
haskell-unicode-snippets 0.1.1 
highlight-selected 0.13.1 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
intentions 1.1.2 
language-autohotkey 0.1.0 
language-computercraft 0.2.1 
language-generic-config 1.3.0 
language-haskell 1.12.1 
language-hjson 0.3.0 
language-kerboscript 0.4.0 
language-kos 0.0.2 
language-lisp 0.2.0 
linter 2.1.4 
linter-ui-default 1.6.0 
markdown-writer 2.6.5 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
omnisharp-atom 0.31.2 
pristine-ui 1.0.15 
project-plus 1.0.0 
python-autopep8 0.1.3 
python-indent 1.0.3 
python-tools 0.6.9 
ramda-syntax 1.0.4 
run-in-terminal 1.0.0 
script 3.15.0 
simple-drag-drop-text 0.3.4 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by laktak** [comment]
@dannyfritz  any idea?

**Comment by dannyfritz** [comment]
I'll have to look at it in a couple weeks. Graduation students this week
and taking vacation next week.

**Comment by dannyfritz** [comment]
I have started looking into this.

onig-reg doesn't like these lines of the regexp:
https://github.com/hjson/atom-hjson/blob/d54a86f581ebaed80420bbc41bb0f4a9fbcd592a/settings/language-hjson.cson#L7
https://github.com/hjson/atom-hjson/blob/d54a86f581ebaed80420bbc41bb0f4a9fbcd592a/settings/language-hjson.cson#L16

It says `[{\[]` is an empty char-class.

Changing it to `[{]` removes the error, but I want to check for `[` too.

It also seems to like `[{\\]]` 🤷‍♂️ .Definitelyy will need to look at it more with more complex test cases.

**Comment by HactarCE** [comment]
But `[}\]]` is fine? Weird...

**Comment by dannyfritz** [comment]
That is correct, `[}\]]` is fine. Or at least I think it is. A more complex test will definitely help me understand this. I'll return to this soon.

**Comment by HactarCE** [comment]
Any progress?

**Comment by dannyfritz** [comment]
`0.4.0` pushed up that fixes this issue.
